// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvqa5BX6coYuABCYTLnHquhNHFrEI4Dmg',
    appId: '1:138112133138:web:070cd0f0d3570e10dc90cb',
    messagingSenderId: '138112133138',
    projectId: 'travel-application-cf740',
    authDomain: 'travel-application-cf740.firebaseapp.com',
    storageBucket: 'travel-application-cf740.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz735w5xWxGZCWDAkd5Uya0qFCyPwShDc',
    appId: '1:138112133138:android:4b81b15f740460e3dc90cb',
    messagingSenderId: '138112133138',
    projectId: 'travel-application-cf740',
    storageBucket: 'travel-application-cf740.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgfG1htCQPYL1_v0CVVCGBuRaBpbBaMN4',
    appId: '1:138112133138:ios:8463851fa3e11e39dc90cb',
    messagingSenderId: '138112133138',
    projectId: 'travel-application-cf740',
    storageBucket: 'travel-application-cf740.appspot.com',
    iosBundleId: 'com.example.travelApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgfG1htCQPYL1_v0CVVCGBuRaBpbBaMN4',
    appId: '1:138112133138:ios:fb0e9c48330ac3e1dc90cb',
    messagingSenderId: '138112133138',
    projectId: 'travel-application-cf740',
    storageBucket: 'travel-application-cf740.appspot.com',
    iosBundleId: 'com.example.travelApplication.RunnerTests',
  );
}
